# Generated by Django 5.1.2 on 2024-11-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Flowers', 'Flowers'), ('Medicinal Planet', 'Medicinal Planet')], max_length=256),
        ),
    ]
